In [1]:
import pandas as pd
import json
from pathlib import Path
from typing import List, Dict, Any

def load_comtrade_data_to_dataframe(base_path: str) -> pd.DataFrame:
    """
    Recursively reads all JSON files from the directory structure
    and combines them into a single pandas DataFrame.
    
    Args:
        base_path: Root directory containing the JSON files
        
    Returns:
        pandas DataFrame with all records from all JSON files
    """
    # Find all JSON files recursively
    json_files = list(Path(base_path).rglob("*.json"))
    print(f"Found {len(json_files)} JSON files")
    
    all_records = []
    
    # Read each JSON file
    for idx, json_file in enumerate(json_files, 1):
        try:
            with open(json_file, 'r') as f:
                data = json.load(f)
            
            # Extract the 'data' array from the JSON
            if isinstance(data, dict) and 'data' in data:
                records = data['data']
                
                # Get the count from the JSON file
                total_count = data.get('count', None)
                
                # Optionally add metadata from the file
                # (filename, year from path structure, etc.)
                for record in records:
                    record['source_file'] = json_file.name
                    record['source_year'] = json_file.parent.name
                    record['total_count'] = total_count
                
                all_records.extend(records)
                
                if idx % 10 == 0:  # Progress indicator
                    print(f"Processed {idx}/{len(json_files)} files, "
                          f"total records: {len(all_records)}")
            else:
                print(f"Unexpected structure in {json_file}")
                
        except Exception as e:
            print(f"Error reading {json_file}: {e}")
            continue
    
    # Convert to DataFrame
    print(f"\nCreating DataFrame with {len(all_records)} total records...")
    df = pd.DataFrame(all_records)
    
    print(f"DataFrame shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    
    return df

# Usage
base_path = "/Users/chromazone/Documents/Python/Data Enginering Zoomcamp/Capstone_monthly/data/bronze/comtrade/monthly_history"
df = load_comtrade_data_to_dataframe(base_path)

# Display info
print("\nDataFrame Info:")
print(df.info())
print("\nFirst few rows:")
print(df.head())
print("\nMemory usage:")
print(f"{df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

Found 288 JSON files
Processed 10/288 files, total records: 30695
Processed 20/288 files, total records: 61360
Processed 30/288 files, total records: 102260
Processed 40/288 files, total records: 143806
Processed 50/288 files, total records: 164510
Processed 60/288 files, total records: 204093
Processed 70/288 files, total records: 265546
Processed 80/288 files, total records: 304123
Processed 90/288 files, total records: 320302
Processed 100/288 files, total records: 349230
Processed 110/288 files, total records: 398959
Processed 120/288 files, total records: 432857
Processed 130/288 files, total records: 475400
Processed 140/288 files, total records: 526242
Processed 150/288 files, total records: 567753
Processed 160/288 files, total records: 611220
Processed 170/288 files, total records: 645854
Processed 180/288 files, total records: 690317
Processed 190/288 files, total records: 758298
Processed 200/288 files, total records: 789640
Processed 210/288 files, total records: 832852
Processed 220/288 files, total records: 877583
Processed 230/288 files, total records: 915221
Processed 240/288 files, total records: 959792
Processed 250/288 files, total records: 982483
Processed 260/288 files, total records: 1014100
Processed 270/288 files, total records: 1032619
Processed 280/288 files, total records: 1068831

Creating DataFrame with 1085896 total records...
DataFrame shape: (1085896, 50)
Columns: ['typeCode', 'freqCode', 'refPeriodId', 'refYear', 'refMonth', 'period', 'reporterCode', 'reporterISO', 'reporterDesc', 'flowCode', 'flowDesc', 'partnerCode', 'partnerISO', 'partnerDesc', 'partner2Code', 'partner2ISO', 'partner2Desc', 'classificationCode', 'classificationSearchCode', 'isOriginalClassification', 'cmdCode', 'cmdDesc', 'aggrLevel', 'isLeaf', 'customsCode', 'customsDesc', 'mosCode', 'motCode', 'motDesc', 'qtyUnitCode', 'qtyUnitAbbr', 'qty', 'isQtyEstimated', 'altQtyUnitCode', 'altQtyUnitAbbr', 'altQty', 'isAltQtyEstimated', 'netWgt', 'isNetWgtEstimated', 'grossWgt', 'isGrossWgtEstimated', 'cifvalue', 'fobvalue', 'primaryValue', 'legacyEstimationFlag', 'isReported', 'isAggregate', 'source_file', 'source_year', 'total_count']

DataFrame Info:
<class 'pandas.DataFrame'>
RangeIndex: 1085896 entries, 0 to 1085895
Data columns (total 50 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   typeCode                  1085896 non-null  str
 1   freqCode                  1085896 non-null  str
 2   refPeriodId               1085896 non-null  int64
 3   refYear                   1085896 non-null  int64
 4   refMonth                  1085896 non-null  int64
 5   period                    1085896 non-null  str
 6   reporterCode              1085896 non-null  int64
 7   reporterISO               1085896 non-null  str
 8   reporterDesc              1085896 non-null  str
 9   flowCode                  1085896 non-null  str
 10  flowDesc                  1085896 non-null  str
 11  partnerCode               1085896 non-null  int64
 12  partnerISO                1085896 non-null  str
 13  partnerDesc               1085896 non-null  str
 14  partner2Code              1085896 non-null  int64
 15  partner2ISO               1085896 non-null  str
 16  partner2Desc              1085896 non-null  str
 17  classificationCode        1085896 non-null  str
 18  classificationSearchCode  1085896 non-null  str
 19  isOriginalClassification  1085896 non-null  bool
 20  cmdCode                   1085896 non-null  str
 21  cmdDesc                   1085896 non-null  str
 22  aggrLevel                 1085896 non-null  int64
 23  isLeaf                    1085896 non-null  bool
 24  customsCode               1085896 non-null  str
 25  customsDesc               1085896 non-null  str
 26  mosCode                   1085896 non-null  str
 27  motCode                   1085896 non-null  int64
 28  motDesc                   1085896 non-null  str
 29  qtyUnitCode               1085896 non-null  int64
 30  qtyUnitAbbr               1085896 non-null  str
 31  qty                       1085896 non-null  float64
 32  isQtyEstimated            1085896 non-null  bool
 33  altQtyUnitCode            1085896 non-null  int64
 34  altQtyUnitAbbr            1085896 non-null  str
 35  altQty                    1085896 non-null  float64
 36  isAltQtyEstimated         1085896 non-null  bool
 37  netWgt                    1080315 non-null  float64
 38  isNetWgtEstimated         1085896 non-null  bool
 39  grossWgt                  1085896 non-null  float64
 40  isGrossWgtEstimated       1085896 non-null  bool
 41  cifvalue                  643751 non-null   float64
 42  fobvalue                  697624 non-null   float64
 43  primaryValue              1085896 non-null  float64
 44  legacyEstimationFlag      1085896 non-null  int64
 45  isReported                1085896 non-null  bool
 46  isAggregate               1085896 non-null  bool
 47  source_file               1085896 non-null  str
 48  source_year               1085896 non-null  str
 49  total_count               1085896 non-null  int64
dtypes: bool(8), float64(7), int64(12), str(23)
memory usage: 678.3 MB
None

First few rows:
  typeCode freqCode  refPeriodId  refYear  refMonth  period  reporterCode  \
0        C        M     20200101     2020         1  202001           724
1        C        M     20200101     2020         1  202001           724
2        C        M     20200101     2020         1  202001           724
3        C        M     20200101     2020         1  202001           724
4        C        M     20200101     2020         1  202001           724

  reporterISO reporterDesc flowCode  ... isGrossWgtEstimated  cifvalue  \
0         ESP        Spain        X  ...               False       0.0
1         ESP        Spain        X  ...               False       0.0
2         ESP        Spain        X  ...               False       0.0
3         ESP        Spain        X  ...               False       0.0
4         ESP        Spain        X  ...               False       0.0

       fobvalue  primaryValue  legacyEstimationFlag isReported isAggregate  \
0  6.530910e+04  6.530910e+04                     0      False        True
1  2.967568e+04  2.967568e+04                     0      False        True
2  1.748716e+04  1.748716e+04                     0      False        True
3  1.626005e+08  1.626005e+08                     0      False        True
4  9.173304e+03  9.173304e+03                     0      False        True

                                         source_file source_year  total_count
0  hist_batch_reps_724_cmd_1001-1005-1006-1201-27...   year=2020        10082
1  hist_batch_reps_724_cmd_1001-1005-1006-1201-27...   year=2020        10082
2  hist_batch_reps_724_cmd_1001-1005-1006-1201-27...   year=2020        10082
3  hist_batch_reps_724_cmd_1001-1005-1006-1201-27...   year=2020        10082
4  hist_batch_reps_724_cmd_1001-1005-1006-1201-27...   year=2020        10082

[5 rows x 50 columns]

Memory usage:
678.34 MB

# Inspect

In [3]:
df.columns

Index(['typeCode', 'freqCode', 'refPeriodId', 'refYear', 'refMonth', 'period',
       'reporterCode', 'reporterISO', 'reporterDesc', 'flowCode', 'flowDesc',
       'partnerCode', 'partnerISO', 'partnerDesc', 'partner2Code',
       'partner2ISO', 'partner2Desc', 'classificationCode',
       'classificationSearchCode', 'isOriginalClassification', 'cmdCode',
       'cmdDesc', 'aggrLevel', 'isLeaf', 'customsCode', 'customsDesc',
       'mosCode', 'motCode', 'motDesc', 'qtyUnitCode', 'qtyUnitAbbr', 'qty',
       'isQtyEstimated', 'altQtyUnitCode', 'altQtyUnitAbbr', 'altQty',
       'isAltQtyEstimated', 'netWgt', 'isNetWgtEstimated', 'grossWgt',
       'isGrossWgtEstimated', 'cifvalue', 'fobvalue', 'primaryValue',
       'legacyEstimationFlag', 'isReported', 'isAggregate', 'source_file',
       'source_year', 'total_count'],
      dtype='str')

In [11]:
df.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate,source_file,source_year,total_count
0,C,M,20200101,2020,1,202001,724,ESP,Spain,X,...,False,0.0,6.530910e+04,6.530910e+04,0,False,True,hist_batch_reps_724_cmd_1001-1005-1006-1201-27...,year=2020,10082
1,C,M,20200101,2020,1,202001,724,ESP,Spain,X,...,False,0.0,2.967568e+04,2.967568e+04,0,False,True,hist_batch_reps_724_cmd_1001-1005-1006-1201-27...,year=2020,10082
2,C,M,20200101,2020,1,202001,724,ESP,Spain,X,...,False,0.0,1.748716e+04,1.748716e+04,0,False,True,hist_batch_reps_724_cmd_1001-1005-1006-1201-27...,year=2020,10082
3,C,M,20200101,2020,1,202001,724,ESP,Spain,X,...,False,0.0,1.626005e+08,1.626005e+08,0,False,True,hist_batch_reps_724_cmd_1001-1005-1006-1201-27...,year=2020,10082
4,C,M,20200101,2020,1,202001,724,ESP,Spain,X,...,False,0.0,9.173304e+03,9.173304e+03,0,False,True,hist_batch_reps_724_cmd_1001-1005-1006-1201-27...,year=2020,10082

In [4]:
df.shape

(1085896, 50)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1085896 entries, 0 to 1085895
Data columns (total 50 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   typeCode                  1085896 non-null  str
 1   freqCode                  1085896 non-null  str
 2   refPeriodId               1085896 non-null  int64
 3   refYear                   1085896 non-null  int64
 4   refMonth                  1085896 non-null  int64
 5   period                    1085896 non-null  str
 6   reporterCode              1085896 non-null  int64
 7   reporterISO               1085896 non-null  str
 8   reporterDesc              1085896 non-null  str
 9   flowCode                  1085896 non-null  str
 10  flowDesc                  1085896 non-null  str
 11  partnerCode               1085896 non-null  int64
 12  partnerISO                1085896 non-null  str
 13  partnerDesc               1085896 non-null  str
 14  partner2Code              1085896 non-null  int64
 15  partner2ISO               1085896 non-null  str
 16  partner2Desc              1085896 non-null  str
 17  classificationCode        1085896 non-null  str
 18  classificationSearchCode  1085896 non-null  str
 19  isOriginalClassification  1085896 non-null  bool
 20  cmdCode                   1085896 non-null  str
 21  cmdDesc                   1085896 non-null  str
 22  aggrLevel                 1085896 non-null  int64
 23  isLeaf                    1085896 non-null  bool
 24  customsCode               1085896 non-null  str
 25  customsDesc               1085896 non-null  str
 26  mosCode                   1085896 non-null  str
 27  motCode                   1085896 non-null  int64
 28  motDesc                   1085896 non-null  str
 29  qtyUnitCode               1085896 non-null  int64
 30  qtyUnitAbbr               1085896 non-null  str
 31  qty                       1085896 non-null  float64
 32  isQtyEstimated            1085896 non-null  bool
 33  altQtyUnitCode            1085896 non-null  int64
 34  altQtyUnitAbbr            1085896 non-null  str
 35  altQty                    1085896 non-null  float64
 36  isAltQtyEstimated         1085896 non-null  bool
 37  netWgt                    1080315 non-null  float64
 38  isNetWgtEstimated         1085896 non-null  bool
 39  grossWgt                  1085896 non-null  float64
 40  isGrossWgtEstimated       1085896 non-null  bool
 41  cifvalue                  643751 non-null   float64
 42  fobvalue                  697624 non-null   float64
 43  primaryValue              1085896 non-null  float64
 44  legacyEstimationFlag      1085896 non-null  int64
 45  isReported                1085896 non-null  bool
 46  isAggregate               1085896 non-null  bool
 47  source_file               1085896 non-null  str
 48  source_year               1085896 non-null  str
 49  total_count               1085896 non-null  int64
dtypes: bool(8), float64(7), int64(12), str(23)
memory usage: 678.3 MB

In [9]:
df.describe(include='all')

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate,source_file,source_year,total_count
count,1085896,1085896,1.085896e+06,1.085896e+06,1.085896e+06,1085896,1.085896e+06,1085896,1085896,1085896,...,1085896,6.437510e+05,6.976240e+05,1.085896e+06,1.085896e+06,1085896,1085896,1085896,1085896,1.085896e+06
unique,1,1,NaN,NaN,NaN,72,NaN,8,8,2,...,1,NaN,NaN,NaN,NaN,1,1,276,6,NaN
top,C,M,NaN,NaN,NaN,202402,NaN,ESP,Spain,M,...,False,NaN,NaN,NaN,NaN,False,True,hist_batch_reps_724_cmd_1001-1005-1006-1201-27...,year=2023,NaN
freq,1085896,1085896,NaN,NaN,NaN,19136,NaN,386429,386429,546901,...,1085896,NaN,NaN,NaN,NaN,1085896,1085896,13030,217518,NaN
mean,NaN,NaN,2.022560e+07,2.022496e+03,6.369271e+00,NaN,4.744877e+02,NaN,NaN,NaN,...,NaN,3.524766e+07,1.629107e+07,2.948400e+07,4.150839e-01,NaN,NaN,NaN,NaN,7.644226e+03
std,NaN,NaN,1.592760e+04,1.594540e+00,3.415543e+00,NaN,2.617131e+02,NaN,NaN,NaN,...,NaN,4.787470e+08,2.383220e+08,3.987534e+08,1.522567e+00,NaN,NaN,NaN,NaN,3.981736e+03
min,NaN,NaN,2.020010e+07,2.020000e+03,1.000000e+00,NaN,9.700000e+01,NaN,NaN,NaN,...,NaN,0.000000e+00,0.000000e+00,1.000000e-02,0.000000e+00,NaN,NaN,NaN,NaN,3.150000e+02
25%,NaN,NaN,2.021080e+07,2.021000e+03,3.000000e+00,NaN,2.510000e+02,NaN,NaN,NaN,...,NaN,1.246970e+02,3.617450e+02,1.466683e+03,0.000000e+00,NaN,NaN,NaN,NaN,3.902000e+03
50%,NaN,NaN,2.023010e+07,2.023000e+03,6.000000e+00,NaN,6.420000e+02,NaN,NaN,NaN,...,NaN,8.068637e+03,2.604319e+04,4.557770e+04,0.000000e+00,NaN,NaN,NaN,NaN,9.642000e+03
75%,NaN,NaN,2.024040e+07,2.024000e+03,9.000000e+00,NaN,7.240000e+02,NaN,NaN,NaN,...,NaN,4.876365e+05,4.473791e+05,9.123523e+05,0.000000e+00,NaN,NaN,NaN,NaN,1.077500e+04
max,NaN,NaN,2.025120e+07,2.025000e+03,1.200000e+01,NaN,8.420000e+02,NaN,NaN,NaN,...,NaN,3.704742e+10,2.016835e+10,3.704742e+10,6.000000e+00,NaN,NaN,NaN,NaN,1.303000e+04

In [ ]:
#Cleaning

In [6]:
df.isnull().sum()

typeCode                         0
freqCode                         0
refPeriodId                      0
refYear                          0
refMonth                         0
period                           0
reporterCode                     0
reporterISO                      0
reporterDesc                     0
flowCode                         0
flowDesc                         0
partnerCode                      0
partnerISO                       0
partnerDesc                      0
partner2Code                     0
partner2ISO                      0
partner2Desc                     0
classificationCode               0
classificationSearchCode         0
isOriginalClassification         0
cmdCode                          0
cmdDesc                          0
aggrLevel                        0
isLeaf                           0
customsCode                      0
customsDesc                      0
mosCode                          0
motCode                          0
motDesc                          0
qtyUnitCode                      0
qtyUnitAbbr                      0
qty                              0
isQtyEstimated                   0
altQtyUnitCode                   0
altQtyUnitAbbr                   0
altQty                           0
isAltQtyEstimated                0
netWgt                        5581
isNetWgtEstimated                0
grossWgt                         0
isGrossWgtEstimated              0
cifvalue                    442145
fobvalue                    388272
primaryValue                     0
legacyEstimationFlag             0
isReported                       0
isAggregate                      0
source_file                      0
source_year                      0
total_count                      0
dtype: int64

In [ ]:
df.isnull().sum()
# df.dropna()
# df.fillna(value)

typeCode                         0
freqCode                         0
refPeriodId                      0
refYear                          0
refMonth                         0
period                           0
reporterCode                     0
reporterISO                      0
reporterDesc                     0
flowCode                         0
flowDesc                         0
partnerCode                      0
partnerISO                       0
partnerDesc                      0
partner2Code                     0
partner2ISO                      0
partner2Desc                     0
classificationCode               0
classificationSearchCode         0
isOriginalClassification         0
cmdCode                          0
cmdDesc                          0
aggrLevel                        0
isLeaf                           0
customsCode                      0
customsDesc                      0
mosCode                          0
motCode                          0
motDesc                          0
qtyUnitCode                      0
qtyUnitAbbr                      0
qty                              0
isQtyEstimated                   0
altQtyUnitCode                   0
altQtyUnitAbbr                   0
altQty                           0
isAltQtyEstimated                0
netWgt                        5581
isNetWgtEstimated                0
grossWgt                         0
isGrossWgtEstimated              0
cifvalue                    442145
fobvalue                    388272
primaryValue                     0
legacyEstimationFlag             0
isReported                       0
isAggregate                      0
source_file                      0
source_year                      0
total_count                      0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [16]:
out_path = Path("data/processed/comtrade_monthly_history_full_ingest.csv")
out_path.parent.mkdir(parents=True, exist_ok=True) 
df.to_csv(out_path, index=False)

In [14]:
df.to_csv("data/processed/comtrade_monthly_history_full_ingest.csv", index=False, mkdirs=True)

TypeError: NDFrame.to_csv() got an unexpected keyword argument 'mkdirs'